/** Sample admin dashboard data for localhost browsing without cloud/API access. */

export const LOCALHOST_NAMES = new Set(["localhost", "127.0.0.1", "::1"]);

export function isAdminLocalhost() {
  return (
    typeof window !== "undefined" &&
    LOCALHOST_NAMES.has(window.location.hostname)
  );
}

const now = Date.now();
const day = 24 * 60 * 60 * 1000;

function mealDays(...days) {
  return JSON.stringify(days);
}

const DEMO_ABSTRACT_AMH_BODY = `Objectives: AMH declines with age, and diminished ovarian reserve (DOR) predicts fewer oocytes and worse IVF outcomes. Chronic inflammation may drive ovarian aging; in animals, reducing it preserves follicles and raises AMH, suggesting aging is modifiable. Whether immunomodulatory treatment improves IVF outcomes remains unknown. Using an age-adjusted AMH (aaAMH) ratio to separate reserve from age, we compared IVF outcomes in women with DOR and normal reserve (NOR), each with or without immunomodulatory treatment.
Methods: Retrospective two-center cohort of women undergoing IVF for reproductive failure. The aaAMH ratio was calculated as AMH divided by the age-specific median (US reference data). Women were classified as having DOR (aaAMH <1.0) or NOR (aaAMH 1.0-2.0), and by receipt of individualized immunomodulatory treatment. Owing to small subgroups, data are median (range) and proportions, without inferential testing.
Results: Nineteen women were analyzed (DOR-treated n=4, NOR-treated n=5, DOR-untreated n=3, NOR-untreated n=7); median aaAMH ratios 0.23, 1.40, 0.94, and 1.40. DOR women were younger than NOR women (median age, 37 vs. 40 years), demonstrating that the ratio identifies DOR independent of chronological age. DOR women had fewer oocytes (median, 5.0 vs. 7.5) but similar embryo numbers (2.0 vs. 2.0) and conversion rates (0.33 vs. 0.32). Notably, DOR-treated women had substantially lower aaAMH ratios than DOR-untreated women (0.23 [0.15-0.34] vs. 0.94 [0.60-1.00]; no overlap), yet comparable clinical pregnancy (3/4 vs. 2/3) and live birth rates (2/4 vs. 1/3). Among NOR women, aaAMH ratios were identical in treated and untreated groups (1.40 vs. 1.40), with similar clinical pregnancy (3/5 vs. 3/7) and live birth rates (2/5 vs. 2/7).
Conclusions: Despite markedly lower age-adjusted ovarian reserve, DOR-treated women achieved clinical pregnancy and live birth rates comparable to DOR-untreated women with higher reserve. These findings suggest that individualized immunomodulatory therapy may improve outcomes in selected women with DOR, warranting larger prospective studies.`;

const DEMO_ABSTRACT_FOLLICLE_BODY = `Objectives: Advanced maternal age is a major cause of declining female fertility, yet how it reshapes the cellular landscape of the human periovulatory follicle at single-cell resolution remains incompletely defined. We aimed to define the cell-type-specific transcriptional, compositional, and intercellular-communication changes associated with advanced maternal age in the human periovulatory follicle.
Methods: We performed single-cell RNA sequencing of human follicular aspirates obtained at 36 hours after hCG administration during in vitro fertilization (IVF) for male-factor infertility, comparing women of optimal maternal age (OMA; 21–29 years) and advanced maternal age (AMA; ≥41 years), and characterized transcriptional, cell-compositional, and intercellular-communication changes across 19 follicular and immune cell types.
Results: Advanced maternal age was associated with two distinct, compartment-specific programs. In the granulosa cell lineage, AMA was marked by a coordinated downregulation of oxidative phosphorylation, together with reduced expression of the ovulatory mediator EDN2, the granulosa-oocyte communication genes IL7R and GJA1, and oxidative stress-protective metallothionein genes. In the immune compartment, multiple myeloid and mononuclear populations upregulated TNFα–NFκB and inflammatory response signaling; this was accompanied by reduced IRF8 in dendritic cells and by an expansion of neutrophils that nonetheless showed broad downregulation of antigen-presenting, phagocytic, and antimicrobial genes, indicating a dysregulated immune response. Intercellular communication was globally weakened and redistributed, with reduced extracellular-matrix and ovulatory signaling and increased immune-adhesion signaling, as the dominant late-ovulatory granulosa signaling hub gave way to immune populations. Notably, canonical senescence signatures were not increased in the granulosa cell lineage.
Conclusions: A cell-type-resolved map of the aging human periovulatory follicle indicates that advanced maternal age drives granulosa cell functional and metabolic decline alongside dysregulated immune remodeling, rather than a uniform senescence program.`;

const SAMPLE_ABSTRACT_BODY = `Objectives: This demo abstract illustrates how the admin dashboard renders submissions locally without cloud access.
Methods: Sample methods describe a multi-center observational design with secondary biomarker analyses.
Results: Localhost sample results show illustrative outcome associations and do not reflect real patient data.
Conclusions: Use this fixture to browse filters, review mode, edit, and other admin abstract tools offline.`;

/**
 * Returns a full set of in-memory fixtures for AdminTab sections.
 * Shapes mirror what the live admin APIs return.
 */
export function buildLocalAdminDemoData() {
  const abstracts = [
    {
      id: "ABS-DEMO-001",
      title: "IVF outcomes by the age-adjusted AMH ratio in women receiving immunomodulatory treatment versus untreated controls: a pilot two-center study",
      category: "ART and Fertility Treatment",
      abstract_submission_type: "Clinical Studies",
      status: "accepted",
      keywords: "IVF, AMH, immunomodulatory treatment",
      abstract: DEMO_ABSTRACT_AMH_BODY,
      word_count: DEMO_ABSTRACT_AMH_BODY.split(/\s+/).filter(Boolean).length,
      presentation_preference: "oral",
      assigned_format: "oral",
      format_assigned_at: now - 2 * day,
      oral_session: null,
      oral_session_assigned_at: null,
      oral_session_email_sent_at: null,
      submission_date: now - 5 * day,
      is_invited_speaker: 0,
      young_investigator: 1,
      possible_young_investigator: 0,
      presenter_name: "Khaliun Dashdeleg",
      presenter_email: "khaliun.dashdeleg@example.com",
      corresponding_name: "Joanne Kwak-Kim",
      corresponding_email: "joanne.kwak-kim@example.com",
      presenter_author_id: "AUTH-1",
      corresponding_author_id: "AUTH-6",
      confirmation_sent_at: now - 4 * day,
      decision_email_sent_at: null,
      format_email_sent_at: null,
      authors: [
        {
          id: "AUTH-1",
          first_name: "Khaliun",
          middle_name: null,
          last_name: "Dashdeleg",
          email: "khaliun.dashdeleg@example.com",
          position: 0,
          is_presenter: 1,
          is_corresponding: 0,
        },
        {
          id: "AUTH-2",
          first_name: "Laura",
          middle_name: "L",
          last_name: "Kanzepolsky",
          email: "laura.kanzepolsky@example.com",
          position: 1,
          is_presenter: 0,
          is_corresponding: 0,
        },
        {
          id: "AUTH-2b",
          first_name: "Maria",
          middle_name: "Dinorah",
          last_name: "Salazar Garcia",
          email: "maria.salazar@example.com",
          position: 2,
          is_presenter: 0,
          is_corresponding: 0,
        },
        {
          id: "AUTH-2c",
          first_name: "Thanh",
          middle_name: null,
          last_name: "Luu",
          email: "thanh.luu@example.com",
          position: 3,
          is_presenter: 0,
          is_corresponding: 0,
        },
        {
          id: "AUTH-2d",
          first_name: "Riyas",
          middle_name: null,
          last_name: "Ali",
          email: "riyas.ali@example.com",
          position: 4,
          is_presenter: 0,
          is_corresponding: 0,
        },
        {
          id: "AUTH-6",
          first_name: "Joanne",
          middle_name: null,
          last_name: "Kwak-Kim",
          email: "joanne.kwak-kim@example.com",
          position: 5,
          is_presenter: 0,
          is_corresponding: 1,
        },
      ],
      affiliations: [
        {
          id: "AFF-1",
          author_name: "Khaliun Dashdeleg",
          department: "Reproductive Medicine and Immunology, Obstetrics and Gynecology",
          institution: "Rosalind Franklin University of Medicine and Science",
          city: "North Chicago",
          country: "USA",
          position: 0,
        },
        {
          id: "AFF-1b",
          author_name: "Laura L Kanzepolsky",
          department: null,
          institution: "CEGYR Medicina Reproductiva",
          city: "Buenos Aires",
          country: "Argentina",
          position: 1,
        },
        {
          id: "AFF-1c",
          author_name: "Maria Dinorah Salazar Garcia",
          department: null,
          institution: "Rush University Medical Center",
          city: "Chicago",
          country: "USA",
          position: 2,
        },
        {
          id: "AFF-1d",
          author_name: "Thanh Luu",
          department: null,
          institution: "Rosalind Franklin University of Medicine and Science",
          city: "North Chicago",
          country: "USA",
          position: 3,
        },
        {
          id: "AFF-1e",
          author_name: "Riyas Ali",
          department: null,
          institution: "Rosalind Franklin University of Medicine and Science",
          city: "North Chicago",
          country: "USA",
          position: 4,
        },
        {
          id: "AFF-1f",
          author_name: "Joanne Kwak-Kim",
          department: "Reproductive Medicine and Immunology, Obstetrics and Gynecology",
          institution: "Rosalind Franklin University of Medicine and Science",
          city: "North Chicago",
          country: "USA",
          position: 5,
        },
      ],
    },
    {
      id: "ABS-DEMO-002",
      title: "A Single-Cell Map of the Aging Human Periovulatory Follicle",
      category: "Novel Technologies and Methods",
      abstract_submission_type: "Basic Studies",
      status: "accepted",
      keywords: "Advanced maternal age, Single-cell RNA sequencing, Preovulatory follicle, Granulosa cell dysfunction, Inflammaging",
      abstract: DEMO_ABSTRACT_FOLLICLE_BODY,
      word_count: DEMO_ABSTRACT_FOLLICLE_BODY.split(/\s+/).filter(Boolean).length,
      presentation_preference: "poster",
      assigned_format: "poster",
      format_assigned_at: now - 2 * day,
      poster_session: null,
      poster_session_assigned_at: null,
      poster_session_email_sent_at: null,
      submission_date: now - 12 * day,
      is_invited_speaker: 0,
      young_investigator: 0,
      possible_young_investigator: 0,
      presenter_name: "Yohan Choi",
      presenter_email: "yohan.choi@example.com",
      corresponding_name: "Yohan Choi",
      corresponding_email: "yohan.choi@example.com",
      presenter_author_id: "AUTH-3",
      corresponding_author_id: "AUTH-3",
      confirmation_sent_at: now - 11 * day,
      decision_email_sent_at: now - 2 * day,
      format_email_sent_at: now - 1 * day,
      authors: [
        {
          id: "AUTH-3",
          first_name: "Yohan",
          middle_name: null,
          last_name: "Choi",
          email: "yohan.choi@example.com",
          position: 0,
          is_presenter: 1,
          is_corresponding: 1,
        },
      ],
      affiliations: [
        {
          id: "AFF-2",
          author_name: "Yohan Choi",
          department: "Obstetrics & Gynecology",
          institution: "University of Kentucky",
          city: "Lexington",
          country: "United States",
          position: 0,
        },
      ],
    },
    {
      id: "ABS-DEMO-003",
      title: "Immune checkpoints at the maternal-fetal interface",
      category: "Immune Regulation in Reproduction",
      abstract_submission_type: "Basic Studies",
      status: "accepted",
      rejection_reason: null,
      keywords: "immune checkpoint, placenta, tolerance",
      abstract: SAMPLE_ABSTRACT_BODY,
      word_count: SAMPLE_ABSTRACT_BODY.split(/\s+/).filter(Boolean).length,
      presentation_preference: "either",
      assigned_format: "oral",
      format_assigned_at: now - 1 * day,
      oral_session: "N4",
      oral_session_assigned_at: now - 1 * day,
      oral_session_email_sent_at: null,
      submission_date: now - 9 * day,
      is_invited_speaker: 0,
      young_investigator: 1,
      possible_young_investigator: 0,
      presenter_name: "Nina Brooks",
      presenter_email: "nina.brooks@example.com",
      corresponding_name: "Nina Brooks",
      corresponding_email: "nina.brooks@example.com",
      presenter_author_id: "AUTH-5",
      corresponding_author_id: "AUTH-5",
      confirmation_sent_at: now - 8 * day,
      decision_email_sent_at: now - 1 * day,
      format_email_sent_at: null,
      authors: [
        {
          id: "AUTH-5",
          first_name: "Nina",
          middle_name: null,
          last_name: "Brooks",
          email: "nina.brooks@example.com",
          position: 0,
          is_presenter: 1,
          is_corresponding: 1,
        },
      ],
      affiliations: [
        {
          id: "AFF-4",
          author_name: "Nina Brooks",
          department: "Immunology",
          institution: "Northern Demo University",
          city: "Toronto",
          country: "Canada",
          position: 0,
        },
      ],
    },
    {
      id: "ABS-DEMO-001b",
      title: "Ovarian aging biomarkers for assisted reproduction outcomes",
      category: "ART and Fertility Treatment",
      abstract_submission_type: "Clinical Studies",
      status: "submitted",
      keywords: "AMH, IVF, ovarian reserve, biomarkers",
      abstract: SAMPLE_ABSTRACT_BODY.replace(
        "illustrates how the admin dashboard renders submissions locally",
        "examines ovarian aging biomarkers used in assisted reproduction",
      ),
      word_count: SAMPLE_ABSTRACT_BODY.split(/\s+/).filter(Boolean).length,
      presentation_preference: "poster",
      assigned_format: null,
      format_assigned_at: null,
      submission_date: now - 3 * day,
      is_invited_speaker: 0,
      young_investigator: 0,
      possible_young_investigator: 0,
      presenter_name: "Alex Rivera",
      presenter_email: "alex.rivera@example.com",
      corresponding_name: "Jordan Lee",
      corresponding_email: "jordan.lee@example.com",
      presenter_author_id: "AUTH-1b",
      corresponding_author_id: "AUTH-2b",
      confirmation_sent_at: null,
      decision_email_sent_at: null,
      format_email_sent_at: null,
      authors: [
        {
          id: "AUTH-1b",
          first_name: "Alex",
          middle_name: null,
          last_name: "Rivera",
          email: "alex.rivera@example.com",
          position: 0,
          is_presenter: 1,
          is_corresponding: 0,
        },
        {
          id: "AUTH-2b",
          first_name: "Jordan",
          middle_name: null,
          last_name: "Lee",
          email: "jordan.lee@example.com",
          position: 1,
          is_presenter: 0,
          is_corresponding: 1,
        },
      ],
      affiliations: [
        {
          id: "AFF-1c",
          author_name: "Alex Rivera",
          department: "Reproductive Medicine",
          institution: "Demo University Hospital",
          city: "Seoul",
          country: "Korea, Republic of",
          position: 0,
        },
        {
          id: "AFF-1d",
          author_name: "Jordan Lee",
          department: "Epidemiology",
          institution: "Demo University Hospital",
          city: "Seoul",
          country: "Korea, Republic of",
          position: 1,
        },
      ],
    },
    {
      id: "ABS-DEMO-INV-001",
      title: "Keynote: Global fertility trends and policy",
      category: "Other",
      abstract_submission_type: "Clinical Studies",
      status: "accepted",
      keywords: "demographics, policy, fertility",
      abstract: SAMPLE_ABSTRACT_BODY.replace(
        "multi-center observational design",
        "invited keynote synthesis",
      ),
      word_count: SAMPLE_ABSTRACT_BODY.split(/\s+/).filter(Boolean).length,
      presentation_preference: "oral",
      assigned_format: "oral",
      format_assigned_at: now - 18 * day,
      submission_date: now - 20 * day,
      is_invited_speaker: 1,
      presenter_name: "Dr. Mina Park",
      presenter_email: "mina.park@example.com",
      corresponding_name: "Dr. Mina Park",
      corresponding_email: "mina.park@example.com",
      presenter_author_id: "AUTH-4",
      corresponding_author_id: "AUTH-4",
      confirmation_sent_at: now - 19 * day,
      decision_email_sent_at: null,
      format_email_sent_at: null,
      authors: [
        {
          id: "AUTH-4",
          first_name: "Mina",
          middle_name: null,
          last_name: "Park",
          email: "mina.park@example.com",
          position: 0,
          is_presenter: 1,
          is_corresponding: 1,
        },
      ],
      affiliations: [
        {
          id: "AFF-3",
          author_name: "Mina Park",
          department: "Obstetrics & Gynecology",
          institution: "National Demo Medical Center",
          city: "Seoul",
          country: "Korea, Republic of",
          position: 0,
        },
      ],
    },
    {
      id: "ABS-DEMO-INV-002",
      title: "Plenary: Endometriosis and reproductive immunology",
      category: "Endometriosis and Reproductive Disorders",
      abstract_submission_type: "Clinical Studies",
      status: "submitted",
      keywords: "endometriosis, inflammation, reproduction",
      abstract: SAMPLE_ABSTRACT_BODY,
      word_count: SAMPLE_ABSTRACT_BODY.split(/\s+/).filter(Boolean).length,
      presentation_preference: "oral",
      assigned_format: null,
      format_assigned_at: null,
      submission_date: now - 7 * day,
      is_invited_speaker: 1,
      presenter_name: "Chris Alvarez",
      presenter_email: "chris.alvarez@example.com",
      corresponding_name: "Chris Alvarez",
      corresponding_email: "chris.alvarez@example.com",
      presenter_author_id: "AUTH-6",
      corresponding_author_id: "AUTH-6",
      confirmation_sent_at: null,
      decision_email_sent_at: null,
      format_email_sent_at: null,
      authors: [
        {
          id: "AUTH-6",
          first_name: "Chris",
          middle_name: null,
          last_name: "Alvarez",
          email: "chris.alvarez@example.com",
          position: 0,
          is_presenter: 1,
          is_corresponding: 1,
        },
      ],
      affiliations: [
        {
          id: "AFF-5",
          author_name: "Chris Alvarez",
          department: "Gynecology",
          institution: "Iberia Demo Institute",
          city: "Madrid",
          country: "Spain",
          position: 0,
        },
      ],
    },
  ];

  const registrations = [
    {
      id: "REG-DEMO-001",
      first_name: "Taylor",
      middle_name: null,
      last_name: "Kim",
      email: "taylor.kim@example.com",
      institution: "Seoul Demo Hospital",
      badge_name: "Taylor Kim",
      ticket_type: "isir-member",
      payment_status: "completed",
      total_price: 650,
      accompanying_count: 1,
      is_invited_speaker: 0,
      opening_reception_attending: 1,
      gala_dinner_attending: 1,
      lunch_days: mealDays("Friday", "Saturday"),
      breakfast_days: mealDays("Saturday", "Sunday"),
      city: "Seoul",
      country: "Korea, Republic of",
      phone: "+82-10-0000-0001",
      cell_phone: null,
      trainee_letter_status: "not_required",
      registration_date: now - 8 * day,
    },
    {
      id: "REG-DEMO-002",
      first_name: "Casey",
      last_name: "Nguyen",
      email: "casey.nguyen@example.com",
      institution: "Pacific Fertility Clinic",
      badge_name: "Casey Nguyen",
      ticket_type: "non-member",
      payment_status: "completed",
      total_price: 850,
      accompanying_count: 0,
      is_invited_speaker: 0,
      opening_reception_attending: 1,
      gala_dinner_attending: 0,
      lunch_days: mealDays("Friday", "Saturday", "Sunday"),
      breakfast_days: mealDays("Friday", "Saturday"),
      city: "San Francisco",
      country: "United States",
      phone: "+1-415-555-0102",
      trainee_letter_status: "not_required",
      registration_date: now - 6 * day,
    },
    {
      id: "REG-DEMO-003",
      first_name: "Riley",
      last_name: "Patel",
      email: "riley.patel@example.com",
      institution: "Demo Medical School",
      badge_name: "Riley Patel",
      ticket_type: "trainee-member",
      payment_status: "pending",
      total_price: 350,
      accompanying_count: 0,
      is_invited_speaker: 0,
      opening_reception_attending: 1,
      gala_dinner_attending: 0,
      lunch_days: mealDays("Saturday"),
      breakfast_days: mealDays("Saturday"),
      city: "London",
      country: "United Kingdom",
      phone: "+44-20-7946-0103",
      trainee_letter_url: "trainee-letters/demo.pdf",
      trainee_letter_status: "pending",
      registration_date: now - 3 * day,
    },
    {
      id: "REG-DEMO-004",
      first_name: "Mina",
      last_name: "Park",
      email: "mina.park@example.com",
      institution: "National Demo Medical Center",
      badge_name: "Mina Park",
      ticket_type: "invited-speaker",
      payment_status: "completed",
      total_price: 0,
      accompanying_count: 1,
      is_invited_speaker: 1,
      opening_reception_attending: 1,
      gala_dinner_attending: 1,
      lunch_days: mealDays("Friday", "Saturday", "Sunday"),
      breakfast_days: mealDays("Friday", "Saturday", "Sunday"),
      city: "Seoul",
      country: "Korea, Republic of",
      phone: "+82-10-0000-0004",
      trainee_letter_status: "not_required",
      registration_date: now - 15 * day,
    },
    {
      id: "REG-DEMO-005",
      first_name: "Jamie",
      last_name: "Okafor",
      email: "jamie.okafor@example.com",
      institution: "Lagos Research Center",
      badge_name: "Jamie Okafor",
      ticket_type: "trainee-non-member",
      payment_status: "completed",
      total_price: 400,
      accompanying_count: 0,
      is_invited_speaker: 0,
      opening_reception_attending: 0,
      gala_dinner_attending: 1,
      lunch_days: mealDays("Sunday"),
      breakfast_days: mealDays("Sunday"),
      city: "Lagos",
      country: "Nigeria",
      phone: "+234-800-000-0105",
      trainee_letter_url: "trainee-letters/demo2.pdf",
      trainee_letter_status: "accepted",
      registration_date: now - 4 * day,
    },
    {
      id: "REG-DEMO-006",
      first_name: "Quinn",
      last_name: "Sato",
      email: "quinn.sato@example.com",
      institution: "Tokyo Day Clinic",
      badge_name: "Quinn Sato",
      ticket_type: "korea-day-pass",
      payment_status: "failed",
      total_price: 150,
      accompanying_count: 0,
      is_invited_speaker: 0,
      opening_reception_attending: 0,
      gala_dinner_attending: 0,
      lunch_days: mealDays("Saturday"),
      breakfast_days: mealDays(),
      day_pass_days: mealDays("Saturday"),
      city: "Tokyo",
      country: "Japan",
      phone: "+81-3-0000-0106",
      trainee_letter_status: "not_required",
      registration_date: now - 2 * day,
    },
  ];

  const visaRequests = [
    {
      id: "VISA-DEMO-001",
      name: "Casey Nguyen",
      affiliation: "Pacific Fertility Clinic",
      country: "United States",
      email: "casey.nguyen@example.com",
      status: "pending",
      registration_proof_r2_key: null,
      registration_proof_filename: null,
      notes: "",
      created_at: now - 5 * day,
    },
    {
      id: "VISA-DEMO-002",
      name: "Mina Park",
      affiliation: "National Demo Medical Center",
      country: "Korea, Republic of",
      email: "mina.park@example.com",
      status: "approved",
      registration_proof_r2_key: null,
      notes: "Invited speaker/chair — proof not required",
      created_at: now - 14 * day,
    },
    {
      id: "VISA-DEMO-003",
      name: "Jamie Okafor",
      affiliation: "Lagos Research Center",
      country: "Nigeria",
      email: "jamie.okafor@example.com",
      status: "rejected",
      registration_proof_r2_key: null,
      notes: "Incomplete documentation (demo)",
      created_at: now - 2 * day,
    },
  ];

  const speakerHotelRegistrations = [
    {
      id: "HOTEL-DEMO-001",
      invited_speaker_email: "mina.park@example.com",
      passport_name: "PARK, Mina",
      nationality: "Korea, Republic of",
      guest_count: 1,
      arrival_date: "2026-11-05",
      departure_date: "2026-11-09",
      phone: "+82-10-0000-0004",
      address_physical: "123 Demo Street, Seoul",
      updated_at: now - 10 * day,
    },
    {
      id: "HOTEL-DEMO-002",
      invited_speaker_email: "chris.alvarez@example.com",
      passport_name: "ALVAREZ, Chris",
      nationality: "Spain",
      guest_count: 0,
      arrival_date: "2026-11-06",
      departure_date: "2026-11-09",
      phone: "+34-600-000-002",
      address_physical: "45 Demo Avenue, Madrid",
      updated_at: now - 6 * day,
    },
  ];

  const reviewerOverview = {
    abstracts_per_reviewer: 5,
    totals: {
      total_reviews: 4,
      total_assignments: 8,
      total_reviewers_with_assignments: 2,
      abstracts_with_reviews: 2,
    },
    reviewers: [
      {
        reviewer_email: "reviewer.one@example.com",
        assigned_count: 2,
        reviewed_count: 2,
        avg_score: 7.4,
        assignments: [
          {
            abstract_id: "ABS-DEMO-001",
            title: abstracts[0].title,
            status: abstracts[0].status,
            review_total: 7.5,
            assigned_at: now - 4 * day,
            review_updated_at: now - 2 * day,
          },
          {
            abstract_id: "ABS-DEMO-003",
            title: abstracts[2].title,
            status: abstracts[2].status,
            review_total: 7.3,
            assigned_at: now - 3 * day,
            review_updated_at: now - 1 * day,
          },
        ],
      },
      {
        reviewer_email: "reviewer.two@example.com",
        assigned_count: 1,
        reviewed_count: 1,
        avg_score: 6.8,
        assignments: [
          {
            abstract_id: "ABS-DEMO-001",
            title: abstracts[0].title,
            status: abstracts[0].status,
            review_total: 7.0,
            assigned_at: now - 3 * day,
            review_updated_at: now - 1 * day,
          },
        ],
      },
      {
        reviewer_email: "reviewer.three@example.com",
        assigned_count: 0,
        reviewed_count: 0,
        avg_score: null,
        assignments: [],
      },
    ],
    abstract_assignments: [
      {
        abstract_id: "ABS-DEMO-003",
        title: abstracts[2].title,
        category: abstracts[2].category,
        assigned_reviewers: 1,
      },
      {
        abstract_id: "ABS-DEMO-001",
        title: abstracts[0].title,
        category: abstracts[0].category,
        assigned_reviewers: 2,
      },
    ],
  };

  const reviewerAccounts = [
    {
      email: "reviewer.one@example.com",
      abstracts_target: 5,
      assigned_count: 2,
      active: 1,
    },
    {
      email: "reviewer.two@example.com",
      abstracts_target: null,
      assigned_count: 1,
      active: 1,
    },
    {
      email: "reviewer.three@example.com",
      abstracts_target: 4,
      assigned_count: 0,
      active: 1,
    },
  ];

  const reviewerAbstractScores = [
    {
      id: "ABS-DEMO-001",
      title: abstracts[0].title,
      category: abstracts[0].category,
      status: abstracts[0].status,
      review_summary: {
        review_count: 1,
        coi_count: 0,
        response_count: 1,
        avg_total: 25.0,
        avg_originality: 5.0,
        avg_clarity: 5.0,
        avg_study_design: 5.0,
        avg_data_analysis: 5.0,
        avg_significance: 5.0,
      },
      reviewer_reviews: [
        {
          reviewer_email: "reviewer.one@example.com",
          originality: 5,
          clarity: 5,
          study_design: 5,
          data_analysis: 5,
          significance: 5,
          total: 25,
          previous_study_notes: "Strong pilot with clear clinical relevance.",
          has_coi: false,
          updated_at: now - 2 * day,
        },
      ],
    },
    {
      id: "ABS-DEMO-002",
      title: abstracts[1].title,
      category: abstracts[1].category,
      status: abstracts[1].status,
      review_summary: {
        review_count: 3,
        coi_count: 0,
        response_count: 3,
        avg_total: 20.67,
        avg_originality: 4.33,
        avg_clarity: 4.0,
        avg_study_design: 4.0,
        avg_data_analysis: 4.0,
        avg_significance: 4.33,
      },
      reviewer_reviews: [
        {
          reviewer_email: "reviewer.one@example.com",
          originality: 5,
          clarity: 4,
          study_design: 4,
          data_analysis: 4,
          significance: 4,
          total: 21,
          previous_study_notes: "Novel single-cell atlas of the periovulatory follicle.",
          has_coi: false,
          updated_at: now - 3 * day,
        },
        {
          reviewer_email: "reviewer.two@example.com",
          originality: 4,
          clarity: 4,
          study_design: 4,
          data_analysis: 4,
          significance: 5,
          total: 21,
          previous_study_notes: "Important aging biology with clear compartment split.",
          has_coi: false,
          updated_at: now - 2 * day,
        },
        {
          reviewer_email: "reviewer.three@example.com",
          originality: 4,
          clarity: 4,
          study_design: 4,
          data_analysis: 4,
          significance: 4,
          total: 20,
          previous_study_notes: "Strong methods; conclusions well supported.",
          has_coi: false,
          updated_at: now - 1 * day,
        },
      ],
    },
    {
      id: "ABS-DEMO-003",
      title: abstracts[2].title,
      category: abstracts[2].category,
      status: abstracts[2].status,
      review_summary: {
        review_count: 1,
        coi_count: 0,
        response_count: 1,
        avg_total: 12.0,
        avg_originality: 2.0,
        avg_clarity: 3.0,
        avg_study_design: 2.0,
        avg_data_analysis: 2.0,
        avg_significance: 3.0,
      },
      reviewer_reviews: [
        {
          reviewer_email: "reviewer.one@example.com",
          originality: 2,
          clarity: 3,
          study_design: 2,
          data_analysis: 2,
          significance: 3,
          total: 12,
          previous_study_notes: "Limited significance for the field.",
          has_coi: false,
          updated_at: now - 1 * day,
        },
      ],
    },
  ];

  const speakerProfileSubmissions = [
    {
      id: "PROFILE-DEMO-001",
      status: "pending",
      speaker_key: null,
      display_name: "Dr. Mina Park",
      affiliation: "National Demo Medical Center",
      email: "mina.park@example.com",
      presentation_title: "Global fertility trends and policy",
      image_position: "center top",
      r2_key: null,
      cv_r2_key: null,
    },
    {
      id: "PROFILE-DEMO-002",
      status: "approved",
      speaker_key: "park-mina",
      display_name: "Alex Rivera",
      affiliation: "Demo University Hospital",
      email: "alex.rivera@example.com",
      presentation_title: "Workshop: biomarkers in ART",
      r2_key: null,
      cv_r2_key: null,
    },
    {
      id: "PROFILE-DEMO-003",
      status: "rejected",
      speaker_key: null,
      display_name: "Chris Alvarez",
      affiliation: "Iberia Demo Institute",
      email: "chris.alvarez@example.com",
      presentation_title: "Endometriosis and reproductive immunology",
      r2_key: null,
      cv_r2_key: null,
    },
  ];

  return {
    abstracts,
    registrations,
    visaRequests,
    speakerHotelRegistrations,
    reviewerOverview,
    reviewerAccounts,
    reviewerAccountsDefault: 5,
    reviewerAbstractScores,
    speakerProfileSubmissions,
  };
}
