/**
 * Bundled speaker list for fallback behavior only:
 * - Worker merge when D1 rows lack tier/static_image for known speaker_key
 * - Vite dev stub for GET /api/speaker-profiles/public
 */
export default [
  {
    tier: "plenary",
    key: "cheong-seok-kim",
    name: "Cheong-Seok Kim",
    affiliation:
      "Center for Collaborative Research on Population and Society at Dongguk University, Seoul.",
    image: "cheong-seok-kim.png",
    imagePosition: "center 10%",
    sortOrder: 0,
  },
  {
    tier: "plenary",
    key: "sam-richards",
    name: "Sam Richards",
    affiliation:
      "Professor at Penn State University and a Distinguished Professor at Konkuk University in Seoul, Korea",
    image: "sam-richards.png",
    imagePosition: "center 30%",
    sortOrder: 1,
  },
  {
    tier: "congress",
    key: "ricardo-barini",
    name: "Ricardo Barini",
    affiliation:
      "Collaborating Professor, University of Campinas (UNICAMP), Brazil",
    image: "Ricardo-Barini.png",
    imagePosition: "center 20%",
    sortOrder: 0,
  },
  {
    tier: "congress",
    key: "lina-bergman",
    name: "Lina Bergman",
    affiliation: "Associate Professor, University of Gothenburg, Sweden",
    image: "lina-bergman.jpg",
    sortOrder: 1,
  },
  {
    tier: "congress",
    key: "marcelo-cavalcante",
    name: "Marcelo Cavalcante",
    affiliation: "Professor, University of Fortaleza (UNIFOR), Brazil",
    image: "marcelo-cavalcante.jpeg",
    imagePosition: "center 20%",
    sortOrder: 2,
  },
  {
    tier: "congress",
    key: "larry-chamley",
    name: "Larry Chamley",
    affiliation:
      "Professor and Head of Department of Obstetrics, Gynaecology and Reproductive Sciences, University of Auckland, New Zealand",
    image: "Larry-Chamley.jpg",
    imagePosition: "center 20%",
    sortOrder: 3,
  },
  {
    tier: "congress",
    key: "anke-diemert",
    name: "Anke Diemert",
    affiliation:
      "University Professorship for Midwifery Science / Obstetrics and Prenatal Medicine, Department of Obstetrics and Prenatal Medicine, University Medical Center Hamburg-Eppendorf, Hamburg, Germany",
    image: "anke-diemert.png",
    imagePosition: "center 20%",
    sortOrder: 4,
  },
  {
    tier: "congress",
    key: "brice-gauilliere",
    name: "Brice Gauilliere",
    affiliation: "Professor, Stanford University School of Medicine",
    image: "brice-gauilliere.jpg",
    sortOrder: 5,
  },
  {
    tier: "congress",
    key: "sylvie-girard",
    name: "Sylvie Girard",
    affiliation:
      "Department of Ob/Gyn, Dept of Immunology, Mayo Clinic, MN, USA",
    image: "Sylvie-Girard.png",
    imagePosition: "center 15%",
    sortOrder: 6,
  },
  {
    tier: "congress",
    key: "nardhy-gomez-lopez",
    name: "Nardhy Gomez-Lopez",
    affiliation:
      "Professor, Washington University School of Medicine in St. Louis",
    image: "nardhy-gomez-lopez.jpg",
    sortOrder: 7,
  },
  {
    tier: "congress",
    key: "ananth-kumar-kammala",
    name: "Ananth Kumar Kammala",
    affiliation: "The University of Texas Medical Branch at Galveston",
    image: "ananth-kammala.jpeg",
    sortOrder: 8,
  },
  {
    tier: "congress",
    key: "shihoko-komine-aizawa",
    name: "Shihoko Komine-Aizawa",
    affiliation: "Professor, Nihon University School of Medicine, Tokyo",
    image: "komine-aizawa.jpg",
    imagePosition: "center 30%",
    sortOrder: 9,
  },
  {
    tier: "congress",
    key: "maciej-kurpisz",
    name: "Maciej Kurpisz",
    affiliation:
      "Institute of Human Genetics, Polish Academy of Sciences, Poznań; Calisia University, Kalisz, Poland",
    image: "maciej-kurpisz.jpg",
    imagePosition: "center 15%",
    sortOrder: 10,
  },
  {
    tier: "congress",
    key: "ja-young-kwon",
    name: "Ja Young Kwon",
    affiliation: "Professor, Yonsei University College of Medicine, Seoul",
    image: "ja-young-kwon.jpeg",
    sortOrder: 11,
  },
  {
    tier: "congress",
    key: "gendie-e-lash",
    name: "Gendie E Lash",
    affiliation:
      "Guangzhou Women and Children's Medical Center, Guangzhou, China",
    image: "gendie-lash.jpg",
    imagePosition: "center 25%",
    sortOrder: 12,
  },
  {
    tier: "congress",
    key: "eun-ju-lee",
    name: "Eun-Ju Lee",
    affiliation: "Professor, Chung-Ang University School of Medicine",
    image: "eun-ju-lee.jpg",
    sortOrder: 13,
  },
  {
    tier: "congress",
    key: "jae-ho-lee",
    name: "Jae Ho Lee",
    affiliation:
      "Division of Cell Gene & Regenerative medicine, CHA University",
    image: "jae-ho-lee.jpg",
    imagePosition: "center 20%",
    sortOrder: 14,
  },
  {
    tier: "congress",
    key: "jung-ryeol-lee",
    name: "Jung Ryeol Lee",
    affiliation: "Professor, Seoul National University College of Medicine",
    image: "jung-ryeol-lee.jpg",
    sortOrder: 15,
  },
  {
    tier: "congress",
    key: "keun-young-lee",
    name: "Keun-Young Lee",
    affiliation:
      "Kangnam Sacred Heart Hospital, Hallym University College of Medicine, Seoul, Korea",
    image: "keun-young-lee.png",
    imagePosition: "center 20%",
    sortOrder: 16,
  },
  {
    tier: "congress",
    key: "sung-ki-lee",
    name: "Sung Ki Lee",
    affiliation:
      "Konyang University College of Medicine, Myung-Gok Medical Research Institute",
    image: "sung-ki-lee.jpg",
    imagePosition: "center 20%",
    sortOrder: 17,
  },
  {
    tier: "congress",
    key: "aihua-liao",
    name: "Aihua Liao",
    affiliation: "Huazhong University of Science and Technology",
    image: "aihua-liao.png",
    sortOrder: 18,
  },
  {
    tier: "congress",
    key: "ramkumar-menon",
    name: "Ramkumar Menon",
    affiliation: "Professor, University of Texas Medical Branch, Galveston",
    image: "ramkumar-menon.jpg",
    imagePosition: "center 40%",
    sortOrder: 19,
  },
  {
    tier: "congress",
    key: "jei-won-moon",
    name: "Jei Won Moon",
    affiliation: "Executive Medical Director, M Fertility Center, Seoul, Korea",
    image: "jei-won-moon.jpg",
    imagePosition: "center 20%",
    sortOrder: 20,
  },
  {
    tier: "congress",
    key: "gil-mor",
    name: "Gil Mor",
    affiliation:
      "Scientific Director and Professor, C.S. Mott Center, Wayne State University, Detroit, MI, USA",
    image: "gil-mor.jpg",
    imagePosition: "center 20%",
    sortOrder: 21,
  },
  {
    tier: "congress",
    key: "takeshi-nagamatsu",
    name: "Takeshi Nagamatsu",
    affiliation: "International University of Health and Welfare",
    image: "Takeshi-Nagamatsu.jpg",
    imagePosition: "center 20%",
    sortOrder: 22,
  },
  {
    tier: "congress",
    key: "joon-cheol-park",
    name: "Joon Cheol Park",
    affiliation: "School of Medicine, Kyungpook National University",
    image: "joon-cheol-park.jpg",
    imagePosition: "center 25%",
    sortOrder: 23,
  },
  {
    tier: "congress",
    key: "marie-pierre-piccinni",
    name: "Marie-Pierre Piccinni",
    affiliation: "Professor, University of Florence, Italy",
    image: "Marie-Pierre-Piccinni.png",
    imagePosition: "center 20%",
    sortOrder: 24,
  },
  {
    tier: "congress",
    key: "trishnia-sinha",
    name: "Trishnia Sinha",
    affiliation:
      "Postdoctoral Researcher, University Medical Center Groningen, the Netherlands",
    image: "Trishnia-Sinha.png",
    imagePosition: "center 20%",
    sortOrder: 25,
  },
  {
    tier: "congress",
    key: "anna-stanhewicz",
    name: "Anna Stanhewicz",
    affiliation: "Associate Professor, University of Iowa",
    image: "anna-stanhewicz.jpg",
    imagePosition: "center 0%",
    sortOrder: 26,
  },
  {
    tier: "congress",
    key: "sayaka-tsuda",
    name: "Sayaka Tsuda",
    affiliation: "University of Toyama, Toyama, Japan",
    image: "sayaka-tsuda.jpg",
    sortOrder: 27,
  },
  {
    tier: "congress",
    key: "li-wu",
    name: "Li Wu",
    affiliation:
      "Reproductive and Genetic Center, The First Affiliated Hospital of University of Science and Technology of China",
    image: "li-wu.png",
    imagePosition: "center 20%",
    sortOrder: 28,
  },
];
